<?php
/**
 * Template Name: Case Study with Sidebar
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

	<div id="content" class="content-area">
		<main id="main" class="site-main content-sidebar" role="main">

			<?php if ( have_posts() ) : ?>

				<?php get_template_part( 'template-parts/loop-header' ); ?>

				<?php /* Start the Loop */ ?>
				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'template-parts/content', 'page' ); ?>

				<?php endwhile; ?>

			<?php else : ?>

				<?php get_template_part( 'template-parts/content', 'none' ); ?>

			<?php endif; ?>

			<?php if( is_page(18208)){  ?> <!-- LANDING PAGE -->

				<section class="caseStudyCats">
					<?php
					   $args = array(
								   'taxonomy' => 'work',
								   'orderby' => 'name',
								   'order'   => 'ASC',
								   'exclude' => 52, // Featured
							   );
					   $cats = get_categories($args);
					   foreach($cats as $cat) {
					?>
						  <article><a href="<?php echo get_category_link( $cat->term_id ) ?>">
							<div class="caseStudyPic" >
								<?php  // echo wp_get_attachment_image_url( $cat->image_id, 'image' );
								// image id is stored as term meta
								$image_id = get_term_meta( $cat->term_id, 'image', true );

								// image data stored in array, second argument is which image size to retrieve
								$image_data = wp_get_attachment_image_src( $image_id, 'full' );

								// image url is the first item in the array (aka 0)
								$image = $image_data[0];

								if ( ! empty( $image ) ) {
									echo '<img src="' . esc_url( $image ) . '" />';
								}
								 ?>
								</div>
							  <div class="caseStudyCatsTitle"><?php echo $cat->name; ?></div>
						  </a></article>
					<?php
					   }
					?>
						<article><a href="/100-ways-to-work/employer-testimonials/">
							<div class="caseStudyPic" >
								<img src="/wp-content/uploads/2019/07/suraj_rajapakse.jpg" /></div>
							  <div class="caseStudyCatsTitle">Employer testimonials</div>
					  </a></article>
				</section>



<div class="so-widget-sow-button callOutButton"><div class="ow-button-base ow-button-align-center">
	<a href="/100-ways-to-work/guidance-and-research/" class="ow-icon-placement-left ow-button-hover">
		<span>
			<span class="sow-icon-fontawesome sow-fas" data-sow-icon=""></span>
			Guidance and research		</span>
	</a>
</div></div>






				<section class="caseStudyHighlight">
					<h1 style="width:100% !important;">Highlighted case studies</h1>
					<?php
						$args = array(
							'posts_per_page' => 4,
							'post_type' => 'casestudy',
							'work'  => 'featured',
							// 'orderby' => 'rand',
							);
							$my_query = new WP_Query( $args );
							if ( $my_query->have_posts() ) :
							while ( $my_query->have_posts() ) : $my_query->the_post();
							get_template_part( 'content', 'casestudyHighlight' );
						?>
					<?php endwhile; endif; ?>
				</section>


			<?php }  ?>

			<?php if( is_page(18436)){  ?><!-- Testimonials PAGE -->

			<section class="testimonials">
				<h2>Testimonials</h2>
				<?php
					$args = array(
						'posts_per_page' => -1,
						'post_type' => 'testimonial',
						'orderby' => 'rand',
						);
						$my_query = new WP_Query( $args );
						if ( $my_query->have_posts() ) :
						while ( $my_query->have_posts() ) : $my_query->the_post();
							$logo_pic = get_post_meta( get_the_ID(), 'logo_pic', 1 );

						get_template_part( 'content', 'casestudy' );
					?>
				<?php endwhile; endif; ?>
			</section>


		<?php }  ?>


		<link rel="stylesheet" id="contact-form-7-css" href="/wp-content/plugins/so-widgets-bundle/icons/fontawesome/style.css?ver=5.2.2" type="text/css" media="all">
		<div class="so-widget-sow-social-media-buttons so-widget-sow-social-media-buttons-atom-28482d211f4c"><h3 class="widget-title">Follow our activity on our social media channels: </h3>
		<div class="social-media-button-container">
			<a class="ow-button-hover sow-social-media-button-twitter sow-social-media-button" title="/twitter.com/womenequalities" aria-label="/twitter.com/womenequalities" target="_blank" rel="noopener noreferrer" href="https://twitter.com/womenequalities" >
			<span><span class="sow-icon-fontawesome sow-fab" data-sow-icon="&#xf099;" ></span></span>
			</a>
			<a class="ow-button-hover sow-social-media-button-linkedin sow-social-media-button" title="linkedin.com/company/government-equalities-office" aria-label="linkedin.com/company/government-equalities-office" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/company/government-equalities-office/" >
			<span><span class="sow-icon-fontawesome sow-fab" data-sow-icon="&#xf0e1;" ></span></span>
			</a>
		</div>
		</div>

		</main><!-- #main -->

		<?php get_sidebar( 'caseStudy' ); ?>
	</div><!-- #content -->
<?php get_footer(); ?>
