<?php
/**
 * Sidebar Case Study
 *
 * Displays on the right of a page
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

responsive_mobile_widgets_before(); // above widgets container hook ?>
	<div id="widgets" class="widget-area right-sidebar caseStudyWidgets" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
		<?php responsive_mobile_widgets(); // above widgets hook ?>



			<?php if( !dynamic_sidebar( 'casestudy-sidebar' ) ) : ?>
				<aside class="widget-wrapper">

					<h3 class="widget-title"><?php _e( 'In Archive', 'responsive-mobile' ); ?></h3>
					<ul>
						<?php wp_get_archives( array( 'type' => 'monthly' ) ); ?>
					</ul>

				</aside><!-- end of .widget-wrapper -->
			<?php endif; //end of right-sidebar ?>

			<aside class="widget-wrapper">
				<h3 class="widget-title">Flexible Working Patterns</h3>
				<ul>
					<?php
					   $args = array(
								   'taxonomy' => 'work',
								   'orderby' => 'name',
								   'order'   => 'ASC',
				   				   'exclude' => 52, // Featured
							   );
					   $cats = get_categories($args);
					   foreach($cats as $cat) {
					?>
						  <li><a href="<?php echo get_category_link( $cat->term_id ) ?>">
							   <?php echo $cat->name; ?>
						  </a></li>
					<?php
					   }
					?>
				</ul>
			</aside><!-- end of .widget-wrapper -->



		<?php responsive_mobile_widgets_end(); // after widgets hook ?>
	</div><!-- end of #widgets -->
<?php responsive_mobile_widgets_after(); // after widgets container hook ?>