<?php
/**
 * Header
 *
 * Displays all information in head, starts the body tag, contains theme header
 * and nav and starts the main content wrapper
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>
<!DOCTYPE html>
<!--[if IE 8 ]>
	<html class="no-js ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9 ]>
	<html class="no-js ie9" <?php language_attributes(); ?>>
<![endif]-->
<!--[if gt IE 9]><!-->
<html <?php language_attributes(); ?>><!--<![endif]-->
	<head>
		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />


		<link rel="apple-touch-icon" sizes="57x57" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/wp-content/themes/wbc-theme/img/laca2020favicon/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="/wp-content/themes/wbc-theme/img/laca2020favicon/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="/wp-content/themes/wbc-theme/img/laca2020favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="/wp-content/themes/wbc-theme/img/laca2020favicon/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/wp-content/themes/wbc-theme/img/laca2020favicon/favicon-16x16.png">
		<link rel="manifest" href="/wp-content/themes/wbc-theme/img/laca2020favicon/manifest.json">

		<link rel="profile" href="http://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

		<?php wp_head(); ?>


		<script type="text/javascript"> var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-148235688-1']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); </script>

		<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet">

	</head>

<body <?php body_class(); ?> itemscope="itemscope" itemtype="http://schema.org/WebPage">

<div id="container" class="site macaTemplate">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'responsive-mobile' ); ?></a>
	<a class="skip-link screen-reader-text" href="#main-navigation"><?php _e( 'Skip to main menu', 'responsive-mobile' ); ?></a>
	<header id="header" class="container-full-width site-header" role="banner" itemscope="itemscope" itemtype="http://schema.org/WPHeader">
		<div class="container">
			<div class="header-row">
				<div id="site-branding">
					<div id="logo">
					<a href="https://www.womensbusinesscouncil.co.uk/be-the-change/" rel="home" itemprop="url" title="Leaders As Change Agents">
					<img src="https://www.womensbusinesscouncil.co.uk/wp-content/themes/wbc-theme/img/logoHeader-laca2020.svg"  alt="Leaders As Change Agents" itemprop="image" >
					</a>
					</div>
				</div>

				<nav id="main-navigation" class="site-navigation" role="navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
					<div class="laca2020Nav">
						<button id="mobile-nav-button"><span class="accessibile-label"><?php _e( 'Mobile menu toggle', 'responsive-mobile' ); ?></span></button>
							<?php wp_nav_menu(
								array(
									'container'       => 'div',
									'container_class' => 'main-nav',
									'theme_location'  => 'laca2020'
								)
							); ?>
					</div>
				</nav><!-- #site-navigation -->




			</div>
		</div>

		<div class="laca2020title flexVerticalCenter">
		<h1><?php echo get_the_title(); ?></h1>


		</div>

			<?php $laca2020_sub_title = get_post_meta( get_the_ID(), 'laca2020_sub_title', true );?>
			<?php if ($laca2020_sub_title) { ?><div class="laca2020_sub_title" ><h4 class="standout"><?php echo $laca2020_sub_title; ?></h4></div><?php } ?>

	</header><!-- #header -->

<!-- <div class="header-title-image"></div> -->
	<div id="wrapper" class="site-content container-full-width">
