name: '(shared functionality) Terraform'

on:
  workflow_call:
    inputs:
      GITHUB_ACTIONS_ENVIRONMENT:
        required: true
        type: string
      TERRAFORM_SERVICE_NAME:
        required: true
        type: string
      TERRAFORM_SERVICE_NAME_HYPHENS:
        required: true
        type: string
      TERRAFORM_ENVIRONMENT_NAME:
        required: true
        type: string
      TERRAFORM_STATE_BUCKET:
        required: true
        type: string
      TERRAFORM_STATE_FILE:
        required: true
        type: string
      TERRAFORM_TFVARS_FILE:
        required: true
        type: string
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID:
        required: true
      TERRAFORM_AWS_SECRET_ACCESS_KEY:
        required: true
      MYSQL_PASSWORD:
        required: true
      BASIC_AUTH_USERNAME:
        required: false
      BASIC_AUTH_PASSWORD:
        required: false
      AUTH_KEY:
        required: true
      SECURE_AUTH_KEY:
        required: true
      LOGGED_IN_KEY:
        required: true
      NONCE_KEY:
        required: true
      AUTH_SALT:
        required: true
      SECURE_AUTH_SALT:
        required: true
      LOGGED_IN_SALT:
        required: true
      NONCE_SALT:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.GITHUB_ACTIONS_ENVIRONMENT }}

    outputs:
      main_app_elastic_beanstalk_code_s3_bucket: ${{ steps.step_elastic_beanstalk_code_s3_bucket.outputs.test }}

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Init Terraform'
        run: |
          terraform init "-backend-config=bucket=${{ inputs.TERRAFORM_STATE_BUCKET }}" "-backend-config=key=${{ inputs.TERRAFORM_STATE_FILE }}" "-backend-config=region=${{ env.AWS_DEFAULT_REGION }}" "-backend-config=access_key=${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}" "-backend-config=secret_key=${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}"
        working-directory: ./terraform

      - name: 'Apply Terraform changes'
        run: |
          terraform apply \
          -var-file "${{ inputs.TERRAFORM_TFVARS_FILE }}" \
          -var "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" \
          -var "BASIC_AUTH_USERNAME=${{ secrets.BASIC_AUTH_USERNAME }}" \
          -var "BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}" \
          -var "AUTH_KEY=${{ secrets.AUTH_KEY }}" \
          -var "SECURE_AUTH_KEY=${{ secrets.SECURE_AUTH_KEY }}" \
          -var "LOGGED_IN_KEY=${{ secrets.LOGGED_IN_KEY }}" \
          -var "NONCE_KEY=${{ secrets.NONCE_KEY }}" \
          -var "AUTH_SALT=${{ secrets.AUTH_SALT }}" \
          -var "SECURE_AUTH_SALT=${{ secrets.SECURE_AUTH_SALT }}" \
          -var "LOGGED_IN_SALT=${{ secrets.LOGGED_IN_SALT }}" \
          -var "NONCE_SALT=${{ secrets.NONCE_SALT }}" \
          -auto-approve
        working-directory: ./terraform

      - name: 'Download the TFState file'
        run: |
          aws s3 cp "s3://${{ inputs.TERRAFORM_STATE_BUCKET }}/${{ inputs.TERRAFORM_STATE_FILE }}" ./current_tf_state.json

      - id: step_elastic_beanstalk_code_s3_bucket
        name: 'Find the name of the Elastic Beanstalk application code versions S3 bucket'
        run: |
          echo test=$(jq -r '.resources[] | select(.name == "main_app_elastic_beanstalk_code_s3_bucket").instances[].attributes.bucket' current_tf_state.json) >> main_app_elastic_beanstalk_code_s3_bucket.txt
          cat main_app_elastic_beanstalk_code_s3_bucket.txt
          cat main_app_elastic_beanstalk_code_s3_bucket.txt >> $GITHUB_OUTPUT
