name: 'Terraform (development)'

on: workflow_dispatch

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  terraform_build_deploy:
    uses: ./.github/workflows/_deploy-shared.yml
    with:
      GITHUB_ACTIONS_ENVIRONMENT: Dev
      TERRAFORM_SERVICE_NAME: wbc_web
      TERRAFORM_SERVICE_NAME_HYPHENS: wbc-web
      TERRAFORM_ENVIRONMENT_NAME: Dev
      TERRAFORM_STATE_BUCKET: uk-gov-equality-hub-terraform-state-bucket
      TERRAFORM_STATE_FILE: wbc-website_dev.tfstate
      TERRAFORM_TFVARS_FILE: dev.tfvars
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
      BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
      AUTH_KEY: ${{ secrets.AUTH_KEY }}
      SECURE_AUTH_KEY: ${{ secrets.SECURE_AUTH_KEY }}
      LOGGED_IN_KEY: ${{ secrets.LOGGED_IN_KEY }}
      NONCE_KEY: ${{ secrets.NONCE_KEY }}
      AUTH_SALT: ${{ secrets.AUTH_SALT }}
      SECURE_AUTH_SALT: ${{ secrets.SECURE_AUTH_SALT }}
      LOGGED_IN_SALT: ${{ secrets.LOGGED_IN_SALT }}
      NONCE_SALT: ${{ secrets.NONCE_SALT }}
